image: node:14

pipelines:
  default:
    - step:
        name: Build and Deploy
        caches:
          - node
        script:
          - apt-get update && apt-get install -y lftp
          - npm install
          - npm run build
          - lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST -e "mirror -R dist /public_html; bye"
        artifacts:
          - dist/**

definitions:
  caches:
    node: ~/.npm
